spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    time-out: ${REDIS_TIME_OUT}
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
server:
  port: ${SERVER_PORT}
jwt:
  secret: ${JWT_SECRET_KEY}
cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET}
      url: ${S3_URL}
    region:
      static: ${S3_STATIC}
      auto: false
    credentials:
      access-Key: ${S3_ACCESS_KEY}
      secret-Key: ${S3_SECRET_KEY}